# **Numpy Introduction**

In [61]:
# pip install numpy

In [62]:
# importing the library
import numpy as np

# What Is an Array ?

An array is a collection of items stored in contiguous memory locations. The items in an array are called elements.


In [63]:
# Leta make an array.
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [64]:
# how to convert an array into 2d array
a2 = a[np.newaxis,: ]
a2

array([[0, 1, 2, 3, 4, 5]])

In [65]:
a2.shape

(1, 6)

# How to make 3D Array

In [66]:
a3 = a2[np.newaxis,:]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

-----

# Creating an Array With Numpy

In [67]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [68]:
a.dtype

dtype('int32')

In [69]:
b = np.array([(1 ,2 ,3 ,4 ,5 ,6 , 7), (4 ,5 , 6, 7, 8, 9, 2)])

In [70]:
b.dtype

dtype('int32')

In [71]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [72]:
print(b)
b.shape

[[1 2 3 4 5 6 7]
 [4 5 6 7 8 9 2]]


(2, 7)

# Intialize arrays

In [73]:
# here if i wnat to make an array of zeros
zeros = np.zeros((3,4)) # (Rows , Columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
zeros.dtype

dtype('float64')

In [75]:
# here if i want to make an array of only ones
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
ones.dtype

dtype('float64')

In [77]:
# here if i wnat to make an array of not only zeroes or ones but other value
full = np.full((2,5),5)
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [78]:
full.dtype

dtype('int32')

# Creating An Identity Metrix

In [79]:
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
identity.dtype

dtype('float64')

# Attributes Of Array

In [81]:
a.shape

(7,)

In [82]:
b.shape

(2, 7)

In [83]:
# here if i wnat to know that which is the array dimention
a.ndim

1

In [84]:
# showing me that the array is 2 dimentional
b.ndim

2

In [85]:
len(a) # gives us the length of the array

7

In [86]:
a.size # gives us the total number of elements in the array

7

# Basic Operation

In [87]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [88]:
b

array([[1, 2, 3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8, 9, 2]])

In [90]:
# subtraction
g = a - b
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3,  5]])

In [91]:
#  Additions
h = a + b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15,  9]])

In [92]:
#  Anther Method Of Addition
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15,  9]])

In [93]:
# Multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 14]])

In [95]:
# Division
l = a/b
l

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 3.5       ]])

In [96]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [98]:
# squere of each elements
a = a**2
a


array([ 1,  4,  9, 16, 25, 36, 49])

In [99]:
b = b**2
b

array([[ 1,  4,  9, 16, 25, 36, 49],
       [16, 25, 36, 49, 64, 81,  4]])