# Numpy (part-2)

In [1]:
# import the library
import numpy as np

In [2]:
# making an array of empty elements
empty = np.empty((2,3))
print(empty)
print('-------------')
print(empty[1]) # printing the o index of the array

[[-1.07665839e-311  1.39755179e-242  1.07667678e-311]
 [ 1.07667678e-311  5.43472210e-323  9.88131292e-324]]
-------------
[1.07667678e-311 5.43472210e-323 9.88131292e-324]


In [3]:
# how to create an array with giving a spacific range
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# how to create an array by giving it a spacific difference even or odd
even = np.arange(0,33,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32])

In [5]:
# array of odd numbers
odd = np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [6]:
# linspace array
lin = np.linspace(0,10,num=5)
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
# making an array by giving our own datatype
a = np.arange(10,dtype=np.float64)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
ones = np.ones(2,dtype=np.int64)
ones

array([1, 1], dtype=int64)

# Sorting of an array

In [10]:
arr = np.array([1,2,3,4,5,6,7,9,8])
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Concatenating of two arrays of One Dimentional (Adding)

In [11]:
a = np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])

In [13]:
# now concatenating
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenating 2D Arrays

In [16]:
x = np.array([[1,2],[5,6]])
y = np.array([[1,2]])

In [17]:
# now concatenate them
z = np.concatenate((x,y))
z

array([[1, 2],
       [5, 6],
       [1, 2]])

# Concatenating 2D arrays Into Axis

In [18]:
w = np.array([[1,2],[3,4]])
y = np.array([[2,3]])

In [19]:
# no concatenating them into axix 0 becuse the the length and size are different from each othr
m = np.concatenate((w,y),axis=0)
m

array([[1, 2],
       [3, 4],
       [2, 3]])

In [20]:
# Now how to concatenate two array with the same size on axis 1
n = np.array([[1,2],[3,4]])
u = np.array([[4,5],[6,7]])

In [21]:
# now cancatenating them on axis 1 because the size and length are same
t = np.concatenate((n,u),axis=1)
t

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])

# How to Make 3D arrays

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [24]:
# chacking the dimention of the array 
array_example.ndim

3

In [25]:
# chacking thr size of the array
array_example.size

24

In [26]:
# length of the array
len(array_example)

3

# How to reshape an array

In [30]:
d = np.array([[[1,2,3,4]],
              [[5,6,7,8]],
               [[3,5,6,7]]])
d

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]],

       [[3, 5, 6, 7]]])

In [31]:
# here first check the the shape of the array
d.shape

(3, 1, 4)

In [33]:
# now here i want ot reshape the the array into 6,2
d1 = d.reshape(6,2)
d1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [3, 5],
       [6, 7]])

# Converting 1D arrays into 2D array

In [36]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [42]:
# now to convert them into 2d array we will add the newaxis function
a[np.newaxis,:]
a.shape
# here it is converted into 2d array

(6,)

In [41]:
c = a[:,np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Indexing And Slicing

In [47]:
a = np.arange(2,20)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [48]:
# now indexing mean selection of each element by you
a[0]

2

In [50]:
# here i wnat to print the 7 value so i will gaive the index value of 7
a[5]

7

In [52]:
# now here i want to print the values from 2 to 9
a[0:8]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# indexing in 2d arrays
b = np.array([[1,2,3,4],[5,6,7,8],[7,5,3,6]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 5, 3, 6]])

In [64]:
b[0]

array([1, 2, 3, 4])

In [65]:
b[2]

array([7, 5, 3, 6])

In [66]:
# now here i want to print those values in b which is less then 5
b[b < 5]

array([1, 2, 3, 4, 3])

In [68]:
# here u can also use the remainder (% ) sigh
# eg : i want to print all those values which is exectly divide by 2
b[b % 2 == 0]

array([2, 4, 6, 8, 6])

In [69]:
b[b % 2 == 1]

array([1, 3, 5, 7, 7, 5, 3])

In [70]:
# how to use two condition
b[(b > 2) & (b < 11)]

array([3, 4, 5, 6, 7, 8, 7, 5, 3, 6])

In [71]:
# how to use the Pipe Operator
b[(b > 2) | (b < 11)]

array([1, 2, 3, 4, 5, 6, 7, 8, 7, 5, 3, 6])