# **Making An Array From a Data Another Array**

In [1]:
# lets import the lirary
import numpy as np

In [2]:
# lets make an array
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [3]:
len(a)

45

In [4]:
# now making an another array from the above array
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

# Stacking (Vertical & Horizontal)

In [5]:
# making an array
a = np.arange(1,10)
b = np.arange(11,20)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
# now stacking the arrays verticallay
d = np.vstack((a,b))
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
# now stackig horizontally
s = np.hstack((a,b))
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

# Metrix Or Metraces

In [15]:
# create a metrix of 3x2
a = np.array([[2,3],[5,6],[3,8]])
a

array([[2, 3],
       [5, 6],
       [3, 8]])

In [16]:
a.ndim

2

In [27]:
# creating a metrix of big data
b = np.arange(0,100,2)
b = b.reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [26]:
# slicing of a metrix
b[1:3 , 3:5]

array([[26, 28],
       [46, 48]])

In [33]:
c = b[0:3, 3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [35]:
# how to get the maximum value in the data set
b.max()

98

In [36]:
b.min()

0

In [37]:
# the sum of th metrix
b.sum()

2450

In [39]:
# here u can also check that the maximum and minimum values on axis = 0 or axis = 1
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [41]:
# getting those values whcih is maximum on columns
b.max(axis=0) # only for columns

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
b.max(axis=1)

array([18, 38, 58, 78, 98])

# Addition on a Metrix